[build]
  command = "npm run build"
  # To ensure that netlify doesn't scan the public secret
  # https://docs.netlify.com/configure-builds/environment-variables/#secrets-scan-omit-keys
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_WORKOS_REDIRECT_URI" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
